/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TBUS_MACROS_H
#define TBUS_MACROS_H


/*   User defined includes.   */


/*   User defined macros.   */
#define TBUS_MAX_ADDR_STRING_LEN                         	256 	/* max length of comunication address for process */
#define TBUS_MAX_ADDR_TEMPLET_STRING_LEN                 	256 	/* max length of address templet string */
#define TBUS_MAX_HOST_URL_LEN                            	128 	/* max number of channels in one host machine */
#define TBUS_MAX_CHANNEL_NUM_PREHOST                     	3000 	/* max number of channels in one host machine */
#define TBUS_MAX_RELAY_NUM_PREHOST                       	3000 	/* max number of relay channels in one host machine */
#define TBUS_MAX_KEY_STRING_LEN                          	256 	/* max length of discription */
#define TBUS_MODE_DISABLE                                	1 	/*  */
#define TBUS_MODE_ENABLE                                 	2 	/*  */
#define TBUS_PEER_CTRL_ONE                               	0 	/*  */
#define TBUS_PEER_CTRL_ALL                               	1 	/*  */



#endif /* TBUS_MACROS_H */
