/* soapH.h
   Generated by gSOAP 2.7.15 from ILogManager.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (8)
#endif

#define soap_default_xsd__int(soap, a) soap_default_int(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#define soap_write_xsd__int(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__int(soap, data), 0) || soap_put_xsd__int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);

#define soap_read_xsd__int(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_sap__MonitorLevel
#define SOAP_TYPE_sap__MonitorLevel (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__MonitorLevel(struct soap*, enum sap__MonitorLevel *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__MonitorLevel(struct soap*, const char*, int, const enum sap__MonitorLevel *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_sap__MonitorLevel2s(struct soap*, enum sap__MonitorLevel);
SOAP_FMAC3 enum sap__MonitorLevel * SOAP_FMAC4 soap_in_sap__MonitorLevel(struct soap*, const char*, enum sap__MonitorLevel *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2sap__MonitorLevel(struct soap*, const char*, enum sap__MonitorLevel *);

#define soap_write_sap__MonitorLevel(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__MonitorLevel(soap, data), 0) || soap_put_sap__MonitorLevel(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__MonitorLevel(struct soap*, const enum sap__MonitorLevel *, const char*, const char*);

#define soap_read_sap__MonitorLevel(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__MonitorLevel(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__MonitorLevel * SOAP_FMAC4 soap_get_sap__MonitorLevel(struct soap*, enum sap__MonitorLevel *, const char*, const char*);

#ifndef SOAP_TYPE_sap__LogType
#define SOAP_TYPE_sap__LogType (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__LogType(struct soap*, enum sap__LogType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__LogType(struct soap*, const char*, int, const enum sap__LogType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_sap__LogType2s(struct soap*, enum sap__LogType);
SOAP_FMAC3 enum sap__LogType * SOAP_FMAC4 soap_in_sap__LogType(struct soap*, const char*, enum sap__LogType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2sap__LogType(struct soap*, const char*, enum sap__LogType *);

#define soap_write_sap__LogType(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__LogType(soap, data), 0) || soap_put_sap__LogType(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__LogType(struct soap*, const enum sap__LogType *, const char*, const char*);

#define soap_read_sap__LogType(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__LogType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__LogType * SOAP_FMAC4 soap_get_sap__LogType(struct soap*, enum sap__LogType *, const char*, const char*);

#ifndef SOAP_TYPE_sap__LogLevel
#define SOAP_TYPE_sap__LogLevel (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__LogLevel(struct soap*, enum sap__LogLevel *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__LogLevel(struct soap*, const char*, int, const enum sap__LogLevel *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_sap__LogLevel2s(struct soap*, enum sap__LogLevel);
SOAP_FMAC3 enum sap__LogLevel * SOAP_FMAC4 soap_in_sap__LogLevel(struct soap*, const char*, enum sap__LogLevel *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2sap__LogLevel(struct soap*, const char*, enum sap__LogLevel *);

#define soap_write_sap__LogLevel(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__LogLevel(soap, data), 0) || soap_put_sap__LogLevel(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__LogLevel(struct soap*, const enum sap__LogLevel *, const char*, const char*);

#define soap_read_sap__LogLevel(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__LogLevel(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__LogLevel * SOAP_FMAC4 soap_get_sap__LogLevel(struct soap*, enum sap__LogLevel *, const char*, const char*);

#ifndef SOAP_TYPE_sap__WriteResult
#define SOAP_TYPE_sap__WriteResult (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteResult(struct soap*, enum sap__WriteResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteResult(struct soap*, const char*, int, const enum sap__WriteResult *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_sap__WriteResult2s(struct soap*, enum sap__WriteResult);
SOAP_FMAC3 enum sap__WriteResult * SOAP_FMAC4 soap_in_sap__WriteResult(struct soap*, const char*, enum sap__WriteResult *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2sap__WriteResult(struct soap*, const char*, enum sap__WriteResult *);

#define soap_write_sap__WriteResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteResult(soap, data), 0) || soap_put_sap__WriteResult(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteResult(struct soap*, const enum sap__WriteResult *, const char*, const char*);

#define soap_read_sap__WriteResult(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__WriteResult * SOAP_FMAC4 soap_get_sap__WriteResult(struct soap*, enum sap__WriteResult *, const char*, const char*);

#ifndef SOAP_TYPE_sap__QueryResult
#define SOAP_TYPE_sap__QueryResult (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryResult(struct soap*, enum sap__QueryResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryResult(struct soap*, const char*, int, const enum sap__QueryResult *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_sap__QueryResult2s(struct soap*, enum sap__QueryResult);
SOAP_FMAC3 enum sap__QueryResult * SOAP_FMAC4 soap_in_sap__QueryResult(struct soap*, const char*, enum sap__QueryResult *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2sap__QueryResult(struct soap*, const char*, enum sap__QueryResult *);

#define soap_write_sap__QueryResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryResult(soap, data), 0) || soap_put_sap__QueryResult(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryResult(struct soap*, const enum sap__QueryResult *, const char*, const char*);

#define soap_read_sap__QueryResult(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__QueryResult * SOAP_FMAC4 soap_get_sap__QueryResult(struct soap*, enum sap__QueryResult *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) ::soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) ::soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) ::soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) ::soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) ::soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_sap__WriteOptLog
#define SOAP_TYPE_sap__WriteOptLog (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteOptLog(struct soap*, struct sap__WriteOptLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteOptLog(struct soap*, const struct sap__WriteOptLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteOptLog(struct soap*, const char*, int, const struct sap__WriteOptLog *, const char*);
SOAP_FMAC3 struct sap__WriteOptLog * SOAP_FMAC4 soap_in_sap__WriteOptLog(struct soap*, const char*, struct sap__WriteOptLog *, const char*);

#define soap_write_sap__WriteOptLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteOptLog(soap, data), 0) || soap_put_sap__WriteOptLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteOptLog(struct soap*, const struct sap__WriteOptLog *, const char*, const char*);

#define soap_read_sap__WriteOptLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteOptLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteOptLog * SOAP_FMAC4 soap_get_sap__WriteOptLog(struct soap*, struct sap__WriteOptLog *, const char*, const char*);

#define soap_new_sap__WriteOptLog(soap, n) ::soap_instantiate_sap__WriteOptLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteOptLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteOptLog * SOAP_FMAC2 soap_instantiate_sap__WriteOptLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteOptLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteOptLogResponse
#define SOAP_TYPE_sap__WriteOptLogResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteOptLogResponse(struct soap*, struct sap__WriteOptLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteOptLogResponse(struct soap*, const struct sap__WriteOptLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteOptLogResponse(struct soap*, const char*, int, const struct sap__WriteOptLogResponse *, const char*);
SOAP_FMAC3 struct sap__WriteOptLogResponse * SOAP_FMAC4 soap_in_sap__WriteOptLogResponse(struct soap*, const char*, struct sap__WriteOptLogResponse *, const char*);

#define soap_write_sap__WriteOptLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteOptLogResponse(soap, data), 0) || soap_put_sap__WriteOptLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteOptLogResponse(struct soap*, const struct sap__WriteOptLogResponse *, const char*, const char*);

#define soap_read_sap__WriteOptLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteOptLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteOptLogResponse * SOAP_FMAC4 soap_get_sap__WriteOptLogResponse(struct soap*, struct sap__WriteOptLogResponse *, const char*, const char*);

#define soap_new_sap__WriteOptLogResponse(soap, n) ::soap_instantiate_sap__WriteOptLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteOptLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteOptLogResponse * SOAP_FMAC2 soap_instantiate_sap__WriteOptLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteOptLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteCMLog
#define SOAP_TYPE_sap__WriteCMLog (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteCMLog(struct soap*, struct sap__WriteCMLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteCMLog(struct soap*, const struct sap__WriteCMLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteCMLog(struct soap*, const char*, int, const struct sap__WriteCMLog *, const char*);
SOAP_FMAC3 struct sap__WriteCMLog * SOAP_FMAC4 soap_in_sap__WriteCMLog(struct soap*, const char*, struct sap__WriteCMLog *, const char*);

#define soap_write_sap__WriteCMLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteCMLog(soap, data), 0) || soap_put_sap__WriteCMLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteCMLog(struct soap*, const struct sap__WriteCMLog *, const char*, const char*);

#define soap_read_sap__WriteCMLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteCMLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteCMLog * SOAP_FMAC4 soap_get_sap__WriteCMLog(struct soap*, struct sap__WriteCMLog *, const char*, const char*);

#define soap_new_sap__WriteCMLog(soap, n) ::soap_instantiate_sap__WriteCMLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteCMLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteCMLog * SOAP_FMAC2 soap_instantiate_sap__WriteCMLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteCMLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteCMLogResponse
#define SOAP_TYPE_sap__WriteCMLogResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteCMLogResponse(struct soap*, struct sap__WriteCMLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteCMLogResponse(struct soap*, const struct sap__WriteCMLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteCMLogResponse(struct soap*, const char*, int, const struct sap__WriteCMLogResponse *, const char*);
SOAP_FMAC3 struct sap__WriteCMLogResponse * SOAP_FMAC4 soap_in_sap__WriteCMLogResponse(struct soap*, const char*, struct sap__WriteCMLogResponse *, const char*);

#define soap_write_sap__WriteCMLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteCMLogResponse(soap, data), 0) || soap_put_sap__WriteCMLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteCMLogResponse(struct soap*, const struct sap__WriteCMLogResponse *, const char*, const char*);

#define soap_read_sap__WriteCMLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteCMLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteCMLogResponse * SOAP_FMAC4 soap_get_sap__WriteCMLogResponse(struct soap*, struct sap__WriteCMLogResponse *, const char*, const char*);

#define soap_new_sap__WriteCMLogResponse(soap, n) ::soap_instantiate_sap__WriteCMLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteCMLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteCMLogResponse * SOAP_FMAC2 soap_instantiate_sap__WriteCMLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteCMLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteMonitorLog
#define SOAP_TYPE_sap__WriteMonitorLog (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteMonitorLog(struct soap*, struct sap__WriteMonitorLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteMonitorLog(struct soap*, const struct sap__WriteMonitorLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteMonitorLog(struct soap*, const char*, int, const struct sap__WriteMonitorLog *, const char*);
SOAP_FMAC3 struct sap__WriteMonitorLog * SOAP_FMAC4 soap_in_sap__WriteMonitorLog(struct soap*, const char*, struct sap__WriteMonitorLog *, const char*);

#define soap_write_sap__WriteMonitorLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteMonitorLog(soap, data), 0) || soap_put_sap__WriteMonitorLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteMonitorLog(struct soap*, const struct sap__WriteMonitorLog *, const char*, const char*);

#define soap_read_sap__WriteMonitorLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteMonitorLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteMonitorLog * SOAP_FMAC4 soap_get_sap__WriteMonitorLog(struct soap*, struct sap__WriteMonitorLog *, const char*, const char*);

#define soap_new_sap__WriteMonitorLog(soap, n) ::soap_instantiate_sap__WriteMonitorLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteMonitorLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteMonitorLog * SOAP_FMAC2 soap_instantiate_sap__WriteMonitorLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteMonitorLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteMonitorLogResponse
#define SOAP_TYPE_sap__WriteMonitorLogResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteMonitorLogResponse(struct soap*, struct sap__WriteMonitorLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteMonitorLogResponse(struct soap*, const struct sap__WriteMonitorLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteMonitorLogResponse(struct soap*, const char*, int, const struct sap__WriteMonitorLogResponse *, const char*);
SOAP_FMAC3 struct sap__WriteMonitorLogResponse * SOAP_FMAC4 soap_in_sap__WriteMonitorLogResponse(struct soap*, const char*, struct sap__WriteMonitorLogResponse *, const char*);

#define soap_write_sap__WriteMonitorLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteMonitorLogResponse(soap, data), 0) || soap_put_sap__WriteMonitorLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteMonitorLogResponse(struct soap*, const struct sap__WriteMonitorLogResponse *, const char*, const char*);

#define soap_read_sap__WriteMonitorLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteMonitorLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteMonitorLogResponse * SOAP_FMAC4 soap_get_sap__WriteMonitorLogResponse(struct soap*, struct sap__WriteMonitorLogResponse *, const char*, const char*);

#define soap_new_sap__WriteMonitorLogResponse(soap, n) ::soap_instantiate_sap__WriteMonitorLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteMonitorLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteMonitorLogResponse * SOAP_FMAC2 soap_instantiate_sap__WriteMonitorLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteMonitorLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteDebugLog
#define SOAP_TYPE_sap__WriteDebugLog (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteDebugLog(struct soap*, struct sap__WriteDebugLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteDebugLog(struct soap*, const struct sap__WriteDebugLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteDebugLog(struct soap*, const char*, int, const struct sap__WriteDebugLog *, const char*);
SOAP_FMAC3 struct sap__WriteDebugLog * SOAP_FMAC4 soap_in_sap__WriteDebugLog(struct soap*, const char*, struct sap__WriteDebugLog *, const char*);

#define soap_write_sap__WriteDebugLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteDebugLog(soap, data), 0) || soap_put_sap__WriteDebugLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteDebugLog(struct soap*, const struct sap__WriteDebugLog *, const char*, const char*);

#define soap_read_sap__WriteDebugLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteDebugLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteDebugLog * SOAP_FMAC4 soap_get_sap__WriteDebugLog(struct soap*, struct sap__WriteDebugLog *, const char*, const char*);

#define soap_new_sap__WriteDebugLog(soap, n) ::soap_instantiate_sap__WriteDebugLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteDebugLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteDebugLog * SOAP_FMAC2 soap_instantiate_sap__WriteDebugLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteDebugLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__WriteDebugLogResponse
#define SOAP_TYPE_sap__WriteDebugLogResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__WriteDebugLogResponse(struct soap*, struct sap__WriteDebugLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__WriteDebugLogResponse(struct soap*, const struct sap__WriteDebugLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__WriteDebugLogResponse(struct soap*, const char*, int, const struct sap__WriteDebugLogResponse *, const char*);
SOAP_FMAC3 struct sap__WriteDebugLogResponse * SOAP_FMAC4 soap_in_sap__WriteDebugLogResponse(struct soap*, const char*, struct sap__WriteDebugLogResponse *, const char*);

#define soap_write_sap__WriteDebugLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__WriteDebugLogResponse(soap, data), 0) || soap_put_sap__WriteDebugLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__WriteDebugLogResponse(struct soap*, const struct sap__WriteDebugLogResponse *, const char*, const char*);

#define soap_read_sap__WriteDebugLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__WriteDebugLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__WriteDebugLogResponse * SOAP_FMAC4 soap_get_sap__WriteDebugLogResponse(struct soap*, struct sap__WriteDebugLogResponse *, const char*, const char*);

#define soap_new_sap__WriteDebugLogResponse(soap, n) ::soap_instantiate_sap__WriteDebugLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__WriteDebugLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__WriteDebugLogResponse * SOAP_FMAC2 soap_instantiate_sap__WriteDebugLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__WriteDebugLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryMonitorLog
#define SOAP_TYPE_sap__QueryMonitorLog (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryMonitorLog(struct soap*, struct sap__QueryMonitorLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryMonitorLog(struct soap*, const struct sap__QueryMonitorLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryMonitorLog(struct soap*, const char*, int, const struct sap__QueryMonitorLog *, const char*);
SOAP_FMAC3 struct sap__QueryMonitorLog * SOAP_FMAC4 soap_in_sap__QueryMonitorLog(struct soap*, const char*, struct sap__QueryMonitorLog *, const char*);

#define soap_write_sap__QueryMonitorLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryMonitorLog(soap, data), 0) || soap_put_sap__QueryMonitorLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryMonitorLog(struct soap*, const struct sap__QueryMonitorLog *, const char*, const char*);

#define soap_read_sap__QueryMonitorLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryMonitorLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryMonitorLog * SOAP_FMAC4 soap_get_sap__QueryMonitorLog(struct soap*, struct sap__QueryMonitorLog *, const char*, const char*);

#define soap_new_sap__QueryMonitorLog(soap, n) ::soap_instantiate_sap__QueryMonitorLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryMonitorLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryMonitorLog * SOAP_FMAC2 soap_instantiate_sap__QueryMonitorLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryMonitorLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryMonitorLogResponse
#define SOAP_TYPE_sap__QueryMonitorLogResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryMonitorLogResponse(struct soap*, struct sap__QueryMonitorLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryMonitorLogResponse(struct soap*, const struct sap__QueryMonitorLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryMonitorLogResponse(struct soap*, const char*, int, const struct sap__QueryMonitorLogResponse *, const char*);
SOAP_FMAC3 struct sap__QueryMonitorLogResponse * SOAP_FMAC4 soap_in_sap__QueryMonitorLogResponse(struct soap*, const char*, struct sap__QueryMonitorLogResponse *, const char*);

#define soap_write_sap__QueryMonitorLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryMonitorLogResponse(soap, data), 0) || soap_put_sap__QueryMonitorLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryMonitorLogResponse(struct soap*, const struct sap__QueryMonitorLogResponse *, const char*, const char*);

#define soap_read_sap__QueryMonitorLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryMonitorLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryMonitorLogResponse * SOAP_FMAC4 soap_get_sap__QueryMonitorLogResponse(struct soap*, struct sap__QueryMonitorLogResponse *, const char*, const char*);

#define soap_new_sap__QueryMonitorLogResponse(soap, n) ::soap_instantiate_sap__QueryMonitorLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryMonitorLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryMonitorLogResponse * SOAP_FMAC2 soap_instantiate_sap__QueryMonitorLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryMonitorLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryDebugLog
#define SOAP_TYPE_sap__QueryDebugLog (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryDebugLog(struct soap*, struct sap__QueryDebugLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryDebugLog(struct soap*, const struct sap__QueryDebugLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryDebugLog(struct soap*, const char*, int, const struct sap__QueryDebugLog *, const char*);
SOAP_FMAC3 struct sap__QueryDebugLog * SOAP_FMAC4 soap_in_sap__QueryDebugLog(struct soap*, const char*, struct sap__QueryDebugLog *, const char*);

#define soap_write_sap__QueryDebugLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryDebugLog(soap, data), 0) || soap_put_sap__QueryDebugLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryDebugLog(struct soap*, const struct sap__QueryDebugLog *, const char*, const char*);

#define soap_read_sap__QueryDebugLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryDebugLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryDebugLog * SOAP_FMAC4 soap_get_sap__QueryDebugLog(struct soap*, struct sap__QueryDebugLog *, const char*, const char*);

#define soap_new_sap__QueryDebugLog(soap, n) ::soap_instantiate_sap__QueryDebugLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryDebugLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryDebugLog * SOAP_FMAC2 soap_instantiate_sap__QueryDebugLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryDebugLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryDebugLogResponse
#define SOAP_TYPE_sap__QueryDebugLogResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryDebugLogResponse(struct soap*, struct sap__QueryDebugLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryDebugLogResponse(struct soap*, const struct sap__QueryDebugLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryDebugLogResponse(struct soap*, const char*, int, const struct sap__QueryDebugLogResponse *, const char*);
SOAP_FMAC3 struct sap__QueryDebugLogResponse * SOAP_FMAC4 soap_in_sap__QueryDebugLogResponse(struct soap*, const char*, struct sap__QueryDebugLogResponse *, const char*);

#define soap_write_sap__QueryDebugLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryDebugLogResponse(soap, data), 0) || soap_put_sap__QueryDebugLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryDebugLogResponse(struct soap*, const struct sap__QueryDebugLogResponse *, const char*, const char*);

#define soap_read_sap__QueryDebugLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryDebugLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryDebugLogResponse * SOAP_FMAC4 soap_get_sap__QueryDebugLogResponse(struct soap*, struct sap__QueryDebugLogResponse *, const char*, const char*);

#define soap_new_sap__QueryDebugLogResponse(soap, n) ::soap_instantiate_sap__QueryDebugLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryDebugLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryDebugLogResponse * SOAP_FMAC2 soap_instantiate_sap__QueryDebugLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryDebugLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryOPTLog
#define SOAP_TYPE_sap__QueryOPTLog (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryOPTLog(struct soap*, struct sap__QueryOPTLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryOPTLog(struct soap*, const struct sap__QueryOPTLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryOPTLog(struct soap*, const char*, int, const struct sap__QueryOPTLog *, const char*);
SOAP_FMAC3 struct sap__QueryOPTLog * SOAP_FMAC4 soap_in_sap__QueryOPTLog(struct soap*, const char*, struct sap__QueryOPTLog *, const char*);

#define soap_write_sap__QueryOPTLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryOPTLog(soap, data), 0) || soap_put_sap__QueryOPTLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryOPTLog(struct soap*, const struct sap__QueryOPTLog *, const char*, const char*);

#define soap_read_sap__QueryOPTLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryOPTLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryOPTLog * SOAP_FMAC4 soap_get_sap__QueryOPTLog(struct soap*, struct sap__QueryOPTLog *, const char*, const char*);

#define soap_new_sap__QueryOPTLog(soap, n) ::soap_instantiate_sap__QueryOPTLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryOPTLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryOPTLog * SOAP_FMAC2 soap_instantiate_sap__QueryOPTLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryOPTLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryOPTLogResponse
#define SOAP_TYPE_sap__QueryOPTLogResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryOPTLogResponse(struct soap*, struct sap__QueryOPTLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryOPTLogResponse(struct soap*, const struct sap__QueryOPTLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryOPTLogResponse(struct soap*, const char*, int, const struct sap__QueryOPTLogResponse *, const char*);
SOAP_FMAC3 struct sap__QueryOPTLogResponse * SOAP_FMAC4 soap_in_sap__QueryOPTLogResponse(struct soap*, const char*, struct sap__QueryOPTLogResponse *, const char*);

#define soap_write_sap__QueryOPTLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryOPTLogResponse(soap, data), 0) || soap_put_sap__QueryOPTLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryOPTLogResponse(struct soap*, const struct sap__QueryOPTLogResponse *, const char*, const char*);

#define soap_read_sap__QueryOPTLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryOPTLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryOPTLogResponse * SOAP_FMAC4 soap_get_sap__QueryOPTLogResponse(struct soap*, struct sap__QueryOPTLogResponse *, const char*, const char*);

#define soap_new_sap__QueryOPTLogResponse(soap, n) ::soap_instantiate_sap__QueryOPTLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryOPTLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryOPTLogResponse * SOAP_FMAC2 soap_instantiate_sap__QueryOPTLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryOPTLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryCMLog
#define SOAP_TYPE_sap__QueryCMLog (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryCMLog(struct soap*, struct sap__QueryCMLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryCMLog(struct soap*, const struct sap__QueryCMLog *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryCMLog(struct soap*, const char*, int, const struct sap__QueryCMLog *, const char*);
SOAP_FMAC3 struct sap__QueryCMLog * SOAP_FMAC4 soap_in_sap__QueryCMLog(struct soap*, const char*, struct sap__QueryCMLog *, const char*);

#define soap_write_sap__QueryCMLog(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryCMLog(soap, data), 0) || soap_put_sap__QueryCMLog(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryCMLog(struct soap*, const struct sap__QueryCMLog *, const char*, const char*);

#define soap_read_sap__QueryCMLog(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryCMLog(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryCMLog * SOAP_FMAC4 soap_get_sap__QueryCMLog(struct soap*, struct sap__QueryCMLog *, const char*, const char*);

#define soap_new_sap__QueryCMLog(soap, n) ::soap_instantiate_sap__QueryCMLog(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryCMLog(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryCMLog * SOAP_FMAC2 soap_instantiate_sap__QueryCMLog(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryCMLog(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryCMLogResponse
#define SOAP_TYPE_sap__QueryCMLogResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryCMLogResponse(struct soap*, struct sap__QueryCMLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryCMLogResponse(struct soap*, const struct sap__QueryCMLogResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryCMLogResponse(struct soap*, const char*, int, const struct sap__QueryCMLogResponse *, const char*);
SOAP_FMAC3 struct sap__QueryCMLogResponse * SOAP_FMAC4 soap_in_sap__QueryCMLogResponse(struct soap*, const char*, struct sap__QueryCMLogResponse *, const char*);

#define soap_write_sap__QueryCMLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryCMLogResponse(soap, data), 0) || soap_put_sap__QueryCMLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryCMLogResponse(struct soap*, const struct sap__QueryCMLogResponse *, const char*, const char*);

#define soap_read_sap__QueryCMLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryCMLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryCMLogResponse * SOAP_FMAC4 soap_get_sap__QueryCMLogResponse(struct soap*, struct sap__QueryCMLogResponse *, const char*, const char*);

#define soap_new_sap__QueryCMLogResponse(soap, n) ::soap_instantiate_sap__QueryCMLogResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryCMLogResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryCMLogResponse * SOAP_FMAC2 soap_instantiate_sap__QueryCMLogResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryCMLogResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__OptLogDataSet
#define SOAP_TYPE_sap__OptLogDataSet (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__OptLogDataSet(struct soap*, struct sap__OptLogDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__OptLogDataSet(struct soap*, const struct sap__OptLogDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__OptLogDataSet(struct soap*, const char*, int, const struct sap__OptLogDataSet *, const char*);
SOAP_FMAC3 struct sap__OptLogDataSet * SOAP_FMAC4 soap_in_sap__OptLogDataSet(struct soap*, const char*, struct sap__OptLogDataSet *, const char*);

#define soap_write_sap__OptLogDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__OptLogDataSet(soap, data), 0) || soap_put_sap__OptLogDataSet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__OptLogDataSet(struct soap*, const struct sap__OptLogDataSet *, const char*, const char*);

#define soap_read_sap__OptLogDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__OptLogDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__OptLogDataSet * SOAP_FMAC4 soap_get_sap__OptLogDataSet(struct soap*, struct sap__OptLogDataSet *, const char*, const char*);

#define soap_new_sap__OptLogDataSet(soap, n) ::soap_instantiate_sap__OptLogDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__OptLogDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__OptLogDataSet * SOAP_FMAC2 soap_instantiate_sap__OptLogDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__OptLogDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__OptLogData
#define SOAP_TYPE_sap__OptLogData (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__OptLogData(struct soap*, struct sap__OptLogData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__OptLogData(struct soap*, const struct sap__OptLogData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__OptLogData(struct soap*, const char*, int, const struct sap__OptLogData *, const char*);
SOAP_FMAC3 struct sap__OptLogData * SOAP_FMAC4 soap_in_sap__OptLogData(struct soap*, const char*, struct sap__OptLogData *, const char*);

#define soap_write_sap__OptLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__OptLogData(soap, data), 0) || soap_put_sap__OptLogData(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__OptLogData(struct soap*, const struct sap__OptLogData *, const char*, const char*);

#define soap_read_sap__OptLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__OptLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__OptLogData * SOAP_FMAC4 soap_get_sap__OptLogData(struct soap*, struct sap__OptLogData *, const char*, const char*);

#define soap_new_sap__OptLogData(soap, n) ::soap_instantiate_sap__OptLogData(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__OptLogData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__OptLogData * SOAP_FMAC2 soap_instantiate_sap__OptLogData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__OptLogData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__CMLogDataSet
#define SOAP_TYPE_sap__CMLogDataSet (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__CMLogDataSet(struct soap*, struct sap__CMLogDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__CMLogDataSet(struct soap*, const struct sap__CMLogDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__CMLogDataSet(struct soap*, const char*, int, const struct sap__CMLogDataSet *, const char*);
SOAP_FMAC3 struct sap__CMLogDataSet * SOAP_FMAC4 soap_in_sap__CMLogDataSet(struct soap*, const char*, struct sap__CMLogDataSet *, const char*);

#define soap_write_sap__CMLogDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__CMLogDataSet(soap, data), 0) || soap_put_sap__CMLogDataSet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__CMLogDataSet(struct soap*, const struct sap__CMLogDataSet *, const char*, const char*);

#define soap_read_sap__CMLogDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__CMLogDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__CMLogDataSet * SOAP_FMAC4 soap_get_sap__CMLogDataSet(struct soap*, struct sap__CMLogDataSet *, const char*, const char*);

#define soap_new_sap__CMLogDataSet(soap, n) ::soap_instantiate_sap__CMLogDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__CMLogDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__CMLogDataSet * SOAP_FMAC2 soap_instantiate_sap__CMLogDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__CMLogDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__CMLogData
#define SOAP_TYPE_sap__CMLogData (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__CMLogData(struct soap*, struct sap__CMLogData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__CMLogData(struct soap*, const struct sap__CMLogData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__CMLogData(struct soap*, const char*, int, const struct sap__CMLogData *, const char*);
SOAP_FMAC3 struct sap__CMLogData * SOAP_FMAC4 soap_in_sap__CMLogData(struct soap*, const char*, struct sap__CMLogData *, const char*);

#define soap_write_sap__CMLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__CMLogData(soap, data), 0) || soap_put_sap__CMLogData(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__CMLogData(struct soap*, const struct sap__CMLogData *, const char*, const char*);

#define soap_read_sap__CMLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__CMLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__CMLogData * SOAP_FMAC4 soap_get_sap__CMLogData(struct soap*, struct sap__CMLogData *, const char*, const char*);

#define soap_new_sap__CMLogData(soap, n) ::soap_instantiate_sap__CMLogData(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__CMLogData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__CMLogData * SOAP_FMAC2 soap_instantiate_sap__CMLogData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__CMLogData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__MonitorLogDataSet
#define SOAP_TYPE_sap__MonitorLogDataSet (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__MonitorLogDataSet(struct soap*, struct sap__MonitorLogDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__MonitorLogDataSet(struct soap*, const struct sap__MonitorLogDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__MonitorLogDataSet(struct soap*, const char*, int, const struct sap__MonitorLogDataSet *, const char*);
SOAP_FMAC3 struct sap__MonitorLogDataSet * SOAP_FMAC4 soap_in_sap__MonitorLogDataSet(struct soap*, const char*, struct sap__MonitorLogDataSet *, const char*);

#define soap_write_sap__MonitorLogDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__MonitorLogDataSet(soap, data), 0) || soap_put_sap__MonitorLogDataSet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__MonitorLogDataSet(struct soap*, const struct sap__MonitorLogDataSet *, const char*, const char*);

#define soap_read_sap__MonitorLogDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__MonitorLogDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__MonitorLogDataSet * SOAP_FMAC4 soap_get_sap__MonitorLogDataSet(struct soap*, struct sap__MonitorLogDataSet *, const char*, const char*);

#define soap_new_sap__MonitorLogDataSet(soap, n) ::soap_instantiate_sap__MonitorLogDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__MonitorLogDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__MonitorLogDataSet * SOAP_FMAC2 soap_instantiate_sap__MonitorLogDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__MonitorLogDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__MonitorLogData
#define SOAP_TYPE_sap__MonitorLogData (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__MonitorLogData(struct soap*, struct sap__MonitorLogData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__MonitorLogData(struct soap*, const struct sap__MonitorLogData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__MonitorLogData(struct soap*, const char*, int, const struct sap__MonitorLogData *, const char*);
SOAP_FMAC3 struct sap__MonitorLogData * SOAP_FMAC4 soap_in_sap__MonitorLogData(struct soap*, const char*, struct sap__MonitorLogData *, const char*);

#define soap_write_sap__MonitorLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__MonitorLogData(soap, data), 0) || soap_put_sap__MonitorLogData(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__MonitorLogData(struct soap*, const struct sap__MonitorLogData *, const char*, const char*);

#define soap_read_sap__MonitorLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__MonitorLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__MonitorLogData * SOAP_FMAC4 soap_get_sap__MonitorLogData(struct soap*, struct sap__MonitorLogData *, const char*, const char*);

#define soap_new_sap__MonitorLogData(soap, n) ::soap_instantiate_sap__MonitorLogData(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__MonitorLogData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__MonitorLogData * SOAP_FMAC2 soap_instantiate_sap__MonitorLogData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__MonitorLogData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__QueryDebugLogDataSet
#define SOAP_TYPE_sap__QueryDebugLogDataSet (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__QueryDebugLogDataSet(struct soap*, struct sap__QueryDebugLogDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__QueryDebugLogDataSet(struct soap*, const struct sap__QueryDebugLogDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__QueryDebugLogDataSet(struct soap*, const char*, int, const struct sap__QueryDebugLogDataSet *, const char*);
SOAP_FMAC3 struct sap__QueryDebugLogDataSet * SOAP_FMAC4 soap_in_sap__QueryDebugLogDataSet(struct soap*, const char*, struct sap__QueryDebugLogDataSet *, const char*);

#define soap_write_sap__QueryDebugLogDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__QueryDebugLogDataSet(soap, data), 0) || soap_put_sap__QueryDebugLogDataSet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__QueryDebugLogDataSet(struct soap*, const struct sap__QueryDebugLogDataSet *, const char*, const char*);

#define soap_read_sap__QueryDebugLogDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__QueryDebugLogDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryDebugLogDataSet * SOAP_FMAC4 soap_get_sap__QueryDebugLogDataSet(struct soap*, struct sap__QueryDebugLogDataSet *, const char*, const char*);

#define soap_new_sap__QueryDebugLogDataSet(soap, n) ::soap_instantiate_sap__QueryDebugLogDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__QueryDebugLogDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__QueryDebugLogDataSet * SOAP_FMAC2 soap_instantiate_sap__QueryDebugLogDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__QueryDebugLogDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_sap__DebugLogData
#define SOAP_TYPE_sap__DebugLogData (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sap__DebugLogData(struct soap*, struct sap__DebugLogData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sap__DebugLogData(struct soap*, const struct sap__DebugLogData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sap__DebugLogData(struct soap*, const char*, int, const struct sap__DebugLogData *, const char*);
SOAP_FMAC3 struct sap__DebugLogData * SOAP_FMAC4 soap_in_sap__DebugLogData(struct soap*, const char*, struct sap__DebugLogData *, const char*);

#define soap_write_sap__DebugLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_sap__DebugLogData(soap, data), 0) || soap_put_sap__DebugLogData(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_sap__DebugLogData(struct soap*, const struct sap__DebugLogData *, const char*, const char*);

#define soap_read_sap__DebugLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_sap__DebugLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__DebugLogData * SOAP_FMAC4 soap_get_sap__DebugLogData(struct soap*, struct sap__DebugLogData *, const char*, const char*);

#define soap_new_sap__DebugLogData(soap, n) ::soap_instantiate_sap__DebugLogData(soap, n, NULL, NULL, NULL)


#define soap_delete_sap__DebugLogData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct sap__DebugLogData * SOAP_FMAC2 soap_instantiate_sap__DebugLogData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_sap__DebugLogData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTosap__WriteResult
#define SOAP_TYPE_PointerTosap__WriteResult (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__WriteResult(struct soap*, enum sap__WriteResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__WriteResult(struct soap*, const char *, int, enum sap__WriteResult *const*, const char *);
SOAP_FMAC3 enum sap__WriteResult ** SOAP_FMAC4 soap_in_PointerTosap__WriteResult(struct soap*, const char*, enum sap__WriteResult **, const char*);

#define soap_write_PointerTosap__WriteResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__WriteResult(soap, data), 0) || soap_put_PointerTosap__WriteResult(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__WriteResult(struct soap*, enum sap__WriteResult *const*, const char*, const char*);

#define soap_read_PointerTosap__WriteResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__WriteResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum sap__WriteResult ** SOAP_FMAC4 soap_get_PointerTosap__WriteResult(struct soap*, enum sap__WriteResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__QueryMonitorLogResponse
#define SOAP_TYPE_PointerTosap__QueryMonitorLogResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__QueryMonitorLogResponse(struct soap*, struct sap__QueryMonitorLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__QueryMonitorLogResponse(struct soap*, const char *, int, struct sap__QueryMonitorLogResponse *const*, const char *);
SOAP_FMAC3 struct sap__QueryMonitorLogResponse ** SOAP_FMAC4 soap_in_PointerTosap__QueryMonitorLogResponse(struct soap*, const char*, struct sap__QueryMonitorLogResponse **, const char*);

#define soap_write_PointerTosap__QueryMonitorLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__QueryMonitorLogResponse(soap, data), 0) || soap_put_PointerTosap__QueryMonitorLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__QueryMonitorLogResponse(struct soap*, struct sap__QueryMonitorLogResponse *const*, const char*, const char*);

#define soap_read_PointerTosap__QueryMonitorLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__QueryMonitorLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryMonitorLogResponse ** SOAP_FMAC4 soap_get_PointerTosap__QueryMonitorLogResponse(struct soap*, struct sap__QueryMonitorLogResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__QueryDebugLogResponse
#define SOAP_TYPE_PointerTosap__QueryDebugLogResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__QueryDebugLogResponse(struct soap*, struct sap__QueryDebugLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__QueryDebugLogResponse(struct soap*, const char *, int, struct sap__QueryDebugLogResponse *const*, const char *);
SOAP_FMAC3 struct sap__QueryDebugLogResponse ** SOAP_FMAC4 soap_in_PointerTosap__QueryDebugLogResponse(struct soap*, const char*, struct sap__QueryDebugLogResponse **, const char*);

#define soap_write_PointerTosap__QueryDebugLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__QueryDebugLogResponse(soap, data), 0) || soap_put_PointerTosap__QueryDebugLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__QueryDebugLogResponse(struct soap*, struct sap__QueryDebugLogResponse *const*, const char*, const char*);

#define soap_read_PointerTosap__QueryDebugLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__QueryDebugLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryDebugLogResponse ** SOAP_FMAC4 soap_get_PointerTosap__QueryDebugLogResponse(struct soap*, struct sap__QueryDebugLogResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__QueryOPTLogResponse
#define SOAP_TYPE_PointerTosap__QueryOPTLogResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__QueryOPTLogResponse(struct soap*, struct sap__QueryOPTLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__QueryOPTLogResponse(struct soap*, const char *, int, struct sap__QueryOPTLogResponse *const*, const char *);
SOAP_FMAC3 struct sap__QueryOPTLogResponse ** SOAP_FMAC4 soap_in_PointerTosap__QueryOPTLogResponse(struct soap*, const char*, struct sap__QueryOPTLogResponse **, const char*);

#define soap_write_PointerTosap__QueryOPTLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__QueryOPTLogResponse(soap, data), 0) || soap_put_PointerTosap__QueryOPTLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__QueryOPTLogResponse(struct soap*, struct sap__QueryOPTLogResponse *const*, const char*, const char*);

#define soap_read_PointerTosap__QueryOPTLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__QueryOPTLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryOPTLogResponse ** SOAP_FMAC4 soap_get_PointerTosap__QueryOPTLogResponse(struct soap*, struct sap__QueryOPTLogResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__QueryCMLogResponse
#define SOAP_TYPE_PointerTosap__QueryCMLogResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__QueryCMLogResponse(struct soap*, struct sap__QueryCMLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__QueryCMLogResponse(struct soap*, const char *, int, struct sap__QueryCMLogResponse *const*, const char *);
SOAP_FMAC3 struct sap__QueryCMLogResponse ** SOAP_FMAC4 soap_in_PointerTosap__QueryCMLogResponse(struct soap*, const char*, struct sap__QueryCMLogResponse **, const char*);

#define soap_write_PointerTosap__QueryCMLogResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__QueryCMLogResponse(soap, data), 0) || soap_put_PointerTosap__QueryCMLogResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__QueryCMLogResponse(struct soap*, struct sap__QueryCMLogResponse *const*, const char*, const char*);

#define soap_read_PointerTosap__QueryCMLogResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__QueryCMLogResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__QueryCMLogResponse ** SOAP_FMAC4 soap_get_PointerTosap__QueryCMLogResponse(struct soap*, struct sap__QueryCMLogResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__OptLogData
#define SOAP_TYPE_PointerTosap__OptLogData (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__OptLogData(struct soap*, struct sap__OptLogData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__OptLogData(struct soap*, const char *, int, struct sap__OptLogData *const*, const char *);
SOAP_FMAC3 struct sap__OptLogData ** SOAP_FMAC4 soap_in_PointerTosap__OptLogData(struct soap*, const char*, struct sap__OptLogData **, const char*);

#define soap_write_PointerTosap__OptLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__OptLogData(soap, data), 0) || soap_put_PointerTosap__OptLogData(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__OptLogData(struct soap*, struct sap__OptLogData *const*, const char*, const char*);

#define soap_read_PointerTosap__OptLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__OptLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__OptLogData ** SOAP_FMAC4 soap_get_PointerTosap__OptLogData(struct soap*, struct sap__OptLogData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__CMLogData
#define SOAP_TYPE_PointerTosap__CMLogData (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__CMLogData(struct soap*, struct sap__CMLogData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__CMLogData(struct soap*, const char *, int, struct sap__CMLogData *const*, const char *);
SOAP_FMAC3 struct sap__CMLogData ** SOAP_FMAC4 soap_in_PointerTosap__CMLogData(struct soap*, const char*, struct sap__CMLogData **, const char*);

#define soap_write_PointerTosap__CMLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__CMLogData(soap, data), 0) || soap_put_PointerTosap__CMLogData(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__CMLogData(struct soap*, struct sap__CMLogData *const*, const char*, const char*);

#define soap_read_PointerTosap__CMLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__CMLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__CMLogData ** SOAP_FMAC4 soap_get_PointerTosap__CMLogData(struct soap*, struct sap__CMLogData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__MonitorLogData
#define SOAP_TYPE_PointerTosap__MonitorLogData (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__MonitorLogData(struct soap*, struct sap__MonitorLogData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__MonitorLogData(struct soap*, const char *, int, struct sap__MonitorLogData *const*, const char *);
SOAP_FMAC3 struct sap__MonitorLogData ** SOAP_FMAC4 soap_in_PointerTosap__MonitorLogData(struct soap*, const char*, struct sap__MonitorLogData **, const char*);

#define soap_write_PointerTosap__MonitorLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__MonitorLogData(soap, data), 0) || soap_put_PointerTosap__MonitorLogData(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__MonitorLogData(struct soap*, struct sap__MonitorLogData *const*, const char*, const char*);

#define soap_read_PointerTosap__MonitorLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__MonitorLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__MonitorLogData ** SOAP_FMAC4 soap_get_PointerTosap__MonitorLogData(struct soap*, struct sap__MonitorLogData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTosap__DebugLogData
#define SOAP_TYPE_PointerTosap__DebugLogData (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosap__DebugLogData(struct soap*, struct sap__DebugLogData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosap__DebugLogData(struct soap*, const char *, int, struct sap__DebugLogData *const*, const char *);
SOAP_FMAC3 struct sap__DebugLogData ** SOAP_FMAC4 soap_in_PointerTosap__DebugLogData(struct soap*, const char*, struct sap__DebugLogData **, const char*);

#define soap_write_PointerTosap__DebugLogData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTosap__DebugLogData(soap, data), 0) || soap_put_PointerTosap__DebugLogData(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosap__DebugLogData(struct soap*, struct sap__DebugLogData *const*, const char*, const char*);

#define soap_read_PointerTosap__DebugLogData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTosap__DebugLogData(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct sap__DebugLogData ** SOAP_FMAC4 soap_get_PointerTosap__DebugLogData(struct soap*, struct sap__DebugLogData **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
