/* soapH.h
   Generated by gSOAP 2.7.15 from IFlowControl.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (8)
#endif

#define soap_default_xsd__int(soap, a) soap_default_int(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#define soap_write_xsd__int(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__int(soap, data), 0) || soap_put_xsd__int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);

#define soap_read_xsd__int(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#define soap_write_unsignedLONG64(soap, data) ( soap_begin_send(soap) || (soap_serialize_unsignedLONG64(soap, data), 0) || soap_put_unsignedLONG64(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, const ULONG64 *, const char*, const char*);

#define soap_read_unsignedLONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedLONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);

#ifndef SOAP_TYPE_fc__CheckResult
#define SOAP_TYPE_fc__CheckResult (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckResult(struct soap*, enum fc__CheckResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckResult(struct soap*, const char*, int, const enum fc__CheckResult *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_fc__CheckResult2s(struct soap*, enum fc__CheckResult);
SOAP_FMAC3 enum fc__CheckResult * SOAP_FMAC4 soap_in_fc__CheckResult(struct soap*, const char*, enum fc__CheckResult *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2fc__CheckResult(struct soap*, const char*, enum fc__CheckResult *);

#define soap_write_fc__CheckResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckResult(soap, data), 0) || soap_put_fc__CheckResult(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckResult(struct soap*, const enum fc__CheckResult *, const char*, const char*);

#define soap_read_fc__CheckResult(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum fc__CheckResult * SOAP_FMAC4 soap_get_fc__CheckResult(struct soap*, enum fc__CheckResult *, const char*, const char*);

#ifndef SOAP_TYPE_fc__AuthResult
#define SOAP_TYPE_fc__AuthResult (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__AuthResult(struct soap*, enum fc__AuthResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__AuthResult(struct soap*, const char*, int, const enum fc__AuthResult *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_fc__AuthResult2s(struct soap*, enum fc__AuthResult);
SOAP_FMAC3 enum fc__AuthResult * SOAP_FMAC4 soap_in_fc__AuthResult(struct soap*, const char*, enum fc__AuthResult *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2fc__AuthResult(struct soap*, const char*, enum fc__AuthResult *);

#define soap_write_fc__AuthResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__AuthResult(soap, data), 0) || soap_put_fc__AuthResult(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__AuthResult(struct soap*, const enum fc__AuthResult *, const char*, const char*);

#define soap_read_fc__AuthResult(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__AuthResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum fc__AuthResult * SOAP_FMAC4 soap_get_fc__AuthResult(struct soap*, enum fc__AuthResult *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) ::soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) ::soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) ::soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) ::soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) ::soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_fc__GetOAName
#define SOAP_TYPE_fc__GetOAName (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__GetOAName(struct soap*, struct fc__GetOAName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__GetOAName(struct soap*, const struct fc__GetOAName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__GetOAName(struct soap*, const char*, int, const struct fc__GetOAName *, const char*);
SOAP_FMAC3 struct fc__GetOAName * SOAP_FMAC4 soap_in_fc__GetOAName(struct soap*, const char*, struct fc__GetOAName *, const char*);

#define soap_write_fc__GetOAName(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__GetOAName(soap, data), 0) || soap_put_fc__GetOAName(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__GetOAName(struct soap*, const struct fc__GetOAName *, const char*, const char*);

#define soap_read_fc__GetOAName(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__GetOAName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__GetOAName * SOAP_FMAC4 soap_get_fc__GetOAName(struct soap*, struct fc__GetOAName *, const char*, const char*);

#define soap_new_fc__GetOAName(soap, n) ::soap_instantiate_fc__GetOAName(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__GetOAName(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__GetOAName * SOAP_FMAC2 soap_instantiate_fc__GetOAName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__GetOAName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__GetOANameResponse
#define SOAP_TYPE_fc__GetOANameResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__GetOANameResponse(struct soap*, struct fc__GetOANameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__GetOANameResponse(struct soap*, const struct fc__GetOANameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__GetOANameResponse(struct soap*, const char*, int, const struct fc__GetOANameResponse *, const char*);
SOAP_FMAC3 struct fc__GetOANameResponse * SOAP_FMAC4 soap_in_fc__GetOANameResponse(struct soap*, const char*, struct fc__GetOANameResponse *, const char*);

#define soap_write_fc__GetOANameResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__GetOANameResponse(soap, data), 0) || soap_put_fc__GetOANameResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__GetOANameResponse(struct soap*, const struct fc__GetOANameResponse *, const char*, const char*);

#define soap_read_fc__GetOANameResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__GetOANameResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__GetOANameResponse * SOAP_FMAC4 soap_get_fc__GetOANameResponse(struct soap*, struct fc__GetOANameResponse *, const char*, const char*);

#define soap_new_fc__GetOANameResponse(soap, n) ::soap_instantiate_fc__GetOANameResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__GetOANameResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__GetOANameResponse * SOAP_FMAC2 soap_instantiate_fc__GetOANameResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__GetOANameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckBatchItemSend
#define SOAP_TYPE_fc__CheckBatchItemSend (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckBatchItemSend(struct soap*, struct fc__CheckBatchItemSend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckBatchItemSend(struct soap*, const struct fc__CheckBatchItemSend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckBatchItemSend(struct soap*, const char*, int, const struct fc__CheckBatchItemSend *, const char*);
SOAP_FMAC3 struct fc__CheckBatchItemSend * SOAP_FMAC4 soap_in_fc__CheckBatchItemSend(struct soap*, const char*, struct fc__CheckBatchItemSend *, const char*);

#define soap_write_fc__CheckBatchItemSend(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckBatchItemSend(soap, data), 0) || soap_put_fc__CheckBatchItemSend(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckBatchItemSend(struct soap*, const struct fc__CheckBatchItemSend *, const char*, const char*);

#define soap_read_fc__CheckBatchItemSend(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckBatchItemSend(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckBatchItemSend * SOAP_FMAC4 soap_get_fc__CheckBatchItemSend(struct soap*, struct fc__CheckBatchItemSend *, const char*, const char*);

#define soap_new_fc__CheckBatchItemSend(soap, n) ::soap_instantiate_fc__CheckBatchItemSend(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckBatchItemSend(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckBatchItemSend * SOAP_FMAC2 soap_instantiate_fc__CheckBatchItemSend(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckBatchItemSend(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckBatchItemSendResponse
#define SOAP_TYPE_fc__CheckBatchItemSendResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckBatchItemSendResponse(struct soap*, struct fc__CheckBatchItemSendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckBatchItemSendResponse(struct soap*, const struct fc__CheckBatchItemSendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckBatchItemSendResponse(struct soap*, const char*, int, const struct fc__CheckBatchItemSendResponse *, const char*);
SOAP_FMAC3 struct fc__CheckBatchItemSendResponse * SOAP_FMAC4 soap_in_fc__CheckBatchItemSendResponse(struct soap*, const char*, struct fc__CheckBatchItemSendResponse *, const char*);

#define soap_write_fc__CheckBatchItemSendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckBatchItemSendResponse(soap, data), 0) || soap_put_fc__CheckBatchItemSendResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckBatchItemSendResponse(struct soap*, const struct fc__CheckBatchItemSendResponse *, const char*, const char*);

#define soap_read_fc__CheckBatchItemSendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckBatchItemSendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckBatchItemSendResponse * SOAP_FMAC4 soap_get_fc__CheckBatchItemSendResponse(struct soap*, struct fc__CheckBatchItemSendResponse *, const char*, const char*);

#define soap_new_fc__CheckBatchItemSendResponse(soap, n) ::soap_instantiate_fc__CheckBatchItemSendResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckBatchItemSendResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckBatchItemSendResponse * SOAP_FMAC2 soap_instantiate_fc__CheckBatchItemSendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckBatchItemSendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckBatchMoneySend
#define SOAP_TYPE_fc__CheckBatchMoneySend (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckBatchMoneySend(struct soap*, struct fc__CheckBatchMoneySend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckBatchMoneySend(struct soap*, const struct fc__CheckBatchMoneySend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckBatchMoneySend(struct soap*, const char*, int, const struct fc__CheckBatchMoneySend *, const char*);
SOAP_FMAC3 struct fc__CheckBatchMoneySend * SOAP_FMAC4 soap_in_fc__CheckBatchMoneySend(struct soap*, const char*, struct fc__CheckBatchMoneySend *, const char*);

#define soap_write_fc__CheckBatchMoneySend(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckBatchMoneySend(soap, data), 0) || soap_put_fc__CheckBatchMoneySend(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckBatchMoneySend(struct soap*, const struct fc__CheckBatchMoneySend *, const char*, const char*);

#define soap_read_fc__CheckBatchMoneySend(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckBatchMoneySend(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckBatchMoneySend * SOAP_FMAC4 soap_get_fc__CheckBatchMoneySend(struct soap*, struct fc__CheckBatchMoneySend *, const char*, const char*);

#define soap_new_fc__CheckBatchMoneySend(soap, n) ::soap_instantiate_fc__CheckBatchMoneySend(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckBatchMoneySend(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckBatchMoneySend * SOAP_FMAC2 soap_instantiate_fc__CheckBatchMoneySend(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckBatchMoneySend(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckBatchMoneySendResponse
#define SOAP_TYPE_fc__CheckBatchMoneySendResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckBatchMoneySendResponse(struct soap*, struct fc__CheckBatchMoneySendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckBatchMoneySendResponse(struct soap*, const struct fc__CheckBatchMoneySendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckBatchMoneySendResponse(struct soap*, const char*, int, const struct fc__CheckBatchMoneySendResponse *, const char*);
SOAP_FMAC3 struct fc__CheckBatchMoneySendResponse * SOAP_FMAC4 soap_in_fc__CheckBatchMoneySendResponse(struct soap*, const char*, struct fc__CheckBatchMoneySendResponse *, const char*);

#define soap_write_fc__CheckBatchMoneySendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckBatchMoneySendResponse(soap, data), 0) || soap_put_fc__CheckBatchMoneySendResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckBatchMoneySendResponse(struct soap*, const struct fc__CheckBatchMoneySendResponse *, const char*, const char*);

#define soap_read_fc__CheckBatchMoneySendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckBatchMoneySendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckBatchMoneySendResponse * SOAP_FMAC4 soap_get_fc__CheckBatchMoneySendResponse(struct soap*, struct fc__CheckBatchMoneySendResponse *, const char*, const char*);

#define soap_new_fc__CheckBatchMoneySendResponse(soap, n) ::soap_instantiate_fc__CheckBatchMoneySendResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckBatchMoneySendResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckBatchMoneySendResponse * SOAP_FMAC2 soap_instantiate_fc__CheckBatchMoneySendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckBatchMoneySendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckItemSend
#define SOAP_TYPE_fc__CheckItemSend (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckItemSend(struct soap*, struct fc__CheckItemSend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckItemSend(struct soap*, const struct fc__CheckItemSend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckItemSend(struct soap*, const char*, int, const struct fc__CheckItemSend *, const char*);
SOAP_FMAC3 struct fc__CheckItemSend * SOAP_FMAC4 soap_in_fc__CheckItemSend(struct soap*, const char*, struct fc__CheckItemSend *, const char*);

#define soap_write_fc__CheckItemSend(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckItemSend(soap, data), 0) || soap_put_fc__CheckItemSend(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckItemSend(struct soap*, const struct fc__CheckItemSend *, const char*, const char*);

#define soap_read_fc__CheckItemSend(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckItemSend(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckItemSend * SOAP_FMAC4 soap_get_fc__CheckItemSend(struct soap*, struct fc__CheckItemSend *, const char*, const char*);

#define soap_new_fc__CheckItemSend(soap, n) ::soap_instantiate_fc__CheckItemSend(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckItemSend(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckItemSend * SOAP_FMAC2 soap_instantiate_fc__CheckItemSend(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckItemSend(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckItemSendResponse
#define SOAP_TYPE_fc__CheckItemSendResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckItemSendResponse(struct soap*, struct fc__CheckItemSendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckItemSendResponse(struct soap*, const struct fc__CheckItemSendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckItemSendResponse(struct soap*, const char*, int, const struct fc__CheckItemSendResponse *, const char*);
SOAP_FMAC3 struct fc__CheckItemSendResponse * SOAP_FMAC4 soap_in_fc__CheckItemSendResponse(struct soap*, const char*, struct fc__CheckItemSendResponse *, const char*);

#define soap_write_fc__CheckItemSendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckItemSendResponse(soap, data), 0) || soap_put_fc__CheckItemSendResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckItemSendResponse(struct soap*, const struct fc__CheckItemSendResponse *, const char*, const char*);

#define soap_read_fc__CheckItemSendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckItemSendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckItemSendResponse * SOAP_FMAC4 soap_get_fc__CheckItemSendResponse(struct soap*, struct fc__CheckItemSendResponse *, const char*, const char*);

#define soap_new_fc__CheckItemSendResponse(soap, n) ::soap_instantiate_fc__CheckItemSendResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckItemSendResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckItemSendResponse * SOAP_FMAC2 soap_instantiate_fc__CheckItemSendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckItemSendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckMoneySend
#define SOAP_TYPE_fc__CheckMoneySend (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckMoneySend(struct soap*, struct fc__CheckMoneySend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckMoneySend(struct soap*, const struct fc__CheckMoneySend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckMoneySend(struct soap*, const char*, int, const struct fc__CheckMoneySend *, const char*);
SOAP_FMAC3 struct fc__CheckMoneySend * SOAP_FMAC4 soap_in_fc__CheckMoneySend(struct soap*, const char*, struct fc__CheckMoneySend *, const char*);

#define soap_write_fc__CheckMoneySend(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckMoneySend(soap, data), 0) || soap_put_fc__CheckMoneySend(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckMoneySend(struct soap*, const struct fc__CheckMoneySend *, const char*, const char*);

#define soap_read_fc__CheckMoneySend(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckMoneySend(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckMoneySend * SOAP_FMAC4 soap_get_fc__CheckMoneySend(struct soap*, struct fc__CheckMoneySend *, const char*, const char*);

#define soap_new_fc__CheckMoneySend(soap, n) ::soap_instantiate_fc__CheckMoneySend(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckMoneySend(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckMoneySend * SOAP_FMAC2 soap_instantiate_fc__CheckMoneySend(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckMoneySend(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CheckMoneySendResponse
#define SOAP_TYPE_fc__CheckMoneySendResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CheckMoneySendResponse(struct soap*, struct fc__CheckMoneySendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CheckMoneySendResponse(struct soap*, const struct fc__CheckMoneySendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CheckMoneySendResponse(struct soap*, const char*, int, const struct fc__CheckMoneySendResponse *, const char*);
SOAP_FMAC3 struct fc__CheckMoneySendResponse * SOAP_FMAC4 soap_in_fc__CheckMoneySendResponse(struct soap*, const char*, struct fc__CheckMoneySendResponse *, const char*);

#define soap_write_fc__CheckMoneySendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CheckMoneySendResponse(soap, data), 0) || soap_put_fc__CheckMoneySendResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CheckMoneySendResponse(struct soap*, const struct fc__CheckMoneySendResponse *, const char*, const char*);

#define soap_read_fc__CheckMoneySendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CheckMoneySendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CheckMoneySendResponse * SOAP_FMAC4 soap_get_fc__CheckMoneySendResponse(struct soap*, struct fc__CheckMoneySendResponse *, const char*, const char*);

#define soap_new_fc__CheckMoneySendResponse(soap, n) ::soap_instantiate_fc__CheckMoneySendResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CheckMoneySendResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CheckMoneySendResponse * SOAP_FMAC2 soap_instantiate_fc__CheckMoneySendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CheckMoneySendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CmAuthByQQ
#define SOAP_TYPE_fc__CmAuthByQQ (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CmAuthByQQ(struct soap*, struct fc__CmAuthByQQ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CmAuthByQQ(struct soap*, const struct fc__CmAuthByQQ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CmAuthByQQ(struct soap*, const char*, int, const struct fc__CmAuthByQQ *, const char*);
SOAP_FMAC3 struct fc__CmAuthByQQ * SOAP_FMAC4 soap_in_fc__CmAuthByQQ(struct soap*, const char*, struct fc__CmAuthByQQ *, const char*);

#define soap_write_fc__CmAuthByQQ(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CmAuthByQQ(soap, data), 0) || soap_put_fc__CmAuthByQQ(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CmAuthByQQ(struct soap*, const struct fc__CmAuthByQQ *, const char*, const char*);

#define soap_read_fc__CmAuthByQQ(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CmAuthByQQ(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CmAuthByQQ * SOAP_FMAC4 soap_get_fc__CmAuthByQQ(struct soap*, struct fc__CmAuthByQQ *, const char*, const char*);

#define soap_new_fc__CmAuthByQQ(soap, n) ::soap_instantiate_fc__CmAuthByQQ(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CmAuthByQQ(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CmAuthByQQ * SOAP_FMAC2 soap_instantiate_fc__CmAuthByQQ(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CmAuthByQQ(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CmAuthByQQResponse
#define SOAP_TYPE_fc__CmAuthByQQResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CmAuthByQQResponse(struct soap*, struct fc__CmAuthByQQResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CmAuthByQQResponse(struct soap*, const struct fc__CmAuthByQQResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CmAuthByQQResponse(struct soap*, const char*, int, const struct fc__CmAuthByQQResponse *, const char*);
SOAP_FMAC3 struct fc__CmAuthByQQResponse * SOAP_FMAC4 soap_in_fc__CmAuthByQQResponse(struct soap*, const char*, struct fc__CmAuthByQQResponse *, const char*);

#define soap_write_fc__CmAuthByQQResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CmAuthByQQResponse(soap, data), 0) || soap_put_fc__CmAuthByQQResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CmAuthByQQResponse(struct soap*, const struct fc__CmAuthByQQResponse *, const char*, const char*);

#define soap_read_fc__CmAuthByQQResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CmAuthByQQResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CmAuthByQQResponse * SOAP_FMAC4 soap_get_fc__CmAuthByQQResponse(struct soap*, struct fc__CmAuthByQQResponse *, const char*, const char*);

#define soap_new_fc__CmAuthByQQResponse(soap, n) ::soap_instantiate_fc__CmAuthByQQResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CmAuthByQQResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CmAuthByQQResponse * SOAP_FMAC2 soap_instantiate_fc__CmAuthByQQResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CmAuthByQQResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CmAuthByUser
#define SOAP_TYPE_fc__CmAuthByUser (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CmAuthByUser(struct soap*, struct fc__CmAuthByUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CmAuthByUser(struct soap*, const struct fc__CmAuthByUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CmAuthByUser(struct soap*, const char*, int, const struct fc__CmAuthByUser *, const char*);
SOAP_FMAC3 struct fc__CmAuthByUser * SOAP_FMAC4 soap_in_fc__CmAuthByUser(struct soap*, const char*, struct fc__CmAuthByUser *, const char*);

#define soap_write_fc__CmAuthByUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CmAuthByUser(soap, data), 0) || soap_put_fc__CmAuthByUser(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CmAuthByUser(struct soap*, const struct fc__CmAuthByUser *, const char*, const char*);

#define soap_read_fc__CmAuthByUser(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CmAuthByUser(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CmAuthByUser * SOAP_FMAC4 soap_get_fc__CmAuthByUser(struct soap*, struct fc__CmAuthByUser *, const char*, const char*);

#define soap_new_fc__CmAuthByUser(soap, n) ::soap_instantiate_fc__CmAuthByUser(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CmAuthByUser(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CmAuthByUser * SOAP_FMAC2 soap_instantiate_fc__CmAuthByUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CmAuthByUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_fc__CmAuthByUserResponse
#define SOAP_TYPE_fc__CmAuthByUserResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_fc__CmAuthByUserResponse(struct soap*, struct fc__CmAuthByUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_fc__CmAuthByUserResponse(struct soap*, const struct fc__CmAuthByUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_fc__CmAuthByUserResponse(struct soap*, const char*, int, const struct fc__CmAuthByUserResponse *, const char*);
SOAP_FMAC3 struct fc__CmAuthByUserResponse * SOAP_FMAC4 soap_in_fc__CmAuthByUserResponse(struct soap*, const char*, struct fc__CmAuthByUserResponse *, const char*);

#define soap_write_fc__CmAuthByUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_fc__CmAuthByUserResponse(soap, data), 0) || soap_put_fc__CmAuthByUserResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_fc__CmAuthByUserResponse(struct soap*, const struct fc__CmAuthByUserResponse *, const char*, const char*);

#define soap_read_fc__CmAuthByUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_fc__CmAuthByUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct fc__CmAuthByUserResponse * SOAP_FMAC4 soap_get_fc__CmAuthByUserResponse(struct soap*, struct fc__CmAuthByUserResponse *, const char*, const char*);

#define soap_new_fc__CmAuthByUserResponse(soap, n) ::soap_instantiate_fc__CmAuthByUserResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_fc__CmAuthByUserResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct fc__CmAuthByUserResponse * SOAP_FMAC2 soap_instantiate_fc__CmAuthByUserResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_fc__CmAuthByUserResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#define soap_write_PointerToxsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToxsd__string(soap, data), 0) || soap_put_PointerToxsd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char **const*, const char*, const char*);

#define soap_read_PointerToxsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTofc__CheckResult
#define SOAP_TYPE_PointerTofc__CheckResult (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofc__CheckResult(struct soap*, enum fc__CheckResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofc__CheckResult(struct soap*, const char *, int, enum fc__CheckResult *const*, const char *);
SOAP_FMAC3 enum fc__CheckResult ** SOAP_FMAC4 soap_in_PointerTofc__CheckResult(struct soap*, const char*, enum fc__CheckResult **, const char*);

#define soap_write_PointerTofc__CheckResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTofc__CheckResult(soap, data), 0) || soap_put_PointerTofc__CheckResult(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofc__CheckResult(struct soap*, enum fc__CheckResult *const*, const char*, const char*);

#define soap_read_PointerTofc__CheckResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTofc__CheckResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum fc__CheckResult ** SOAP_FMAC4 soap_get_PointerTofc__CheckResult(struct soap*, enum fc__CheckResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTofc__AuthResult
#define SOAP_TYPE_PointerTofc__AuthResult (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofc__AuthResult(struct soap*, enum fc__AuthResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofc__AuthResult(struct soap*, const char *, int, enum fc__AuthResult *const*, const char *);
SOAP_FMAC3 enum fc__AuthResult ** SOAP_FMAC4 soap_in_PointerTofc__AuthResult(struct soap*, const char*, enum fc__AuthResult **, const char*);

#define soap_write_PointerTofc__AuthResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTofc__AuthResult(soap, data), 0) || soap_put_PointerTofc__AuthResult(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofc__AuthResult(struct soap*, enum fc__AuthResult *const*, const char*, const char*);

#define soap_read_PointerTofc__AuthResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTofc__AuthResult(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum fc__AuthResult ** SOAP_FMAC4 soap_get_PointerTofc__AuthResult(struct soap*, enum fc__AuthResult **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
