/* soapH.h
   Generated by gSOAP 2.7.15 from IDBManager.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (8)
#endif

#define soap_default_xsd__int(soap, a) soap_default_int(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#define soap_write_xsd__int(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__int(soap, data), 0) || soap_put_xsd__int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);

#define soap_read_xsd__int(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (10)
#endif

#define soap_default_xsd__long(soap, a) soap_default_LONG64(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#define soap_write_xsd__long(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__long(soap, data), 0) || soap_put_xsd__long(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, const LONG64 *, const char*, const char*);

#define soap_read_xsd__long(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__long(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || (soap_serialize_LONG64(soap, data), 0) || soap_put_LONG64(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) ::soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) ::soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) ::soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) ::soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) ::soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_dbm__QuerierByAlias
#define SOAP_TYPE_dbm__QuerierByAlias (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__QuerierByAlias(struct soap*, struct dbm__QuerierByAlias *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__QuerierByAlias(struct soap*, const struct dbm__QuerierByAlias *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__QuerierByAlias(struct soap*, const char*, int, const struct dbm__QuerierByAlias *, const char*);
SOAP_FMAC3 struct dbm__QuerierByAlias * SOAP_FMAC4 soap_in_dbm__QuerierByAlias(struct soap*, const char*, struct dbm__QuerierByAlias *, const char*);

#define soap_write_dbm__QuerierByAlias(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__QuerierByAlias(soap, data), 0) || soap_put_dbm__QuerierByAlias(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__QuerierByAlias(struct soap*, const struct dbm__QuerierByAlias *, const char*, const char*);

#define soap_read_dbm__QuerierByAlias(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__QuerierByAlias(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__QuerierByAlias * SOAP_FMAC4 soap_get_dbm__QuerierByAlias(struct soap*, struct dbm__QuerierByAlias *, const char*, const char*);

#define soap_new_dbm__QuerierByAlias(soap, n) ::soap_instantiate_dbm__QuerierByAlias(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__QuerierByAlias(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__QuerierByAlias * SOAP_FMAC2 soap_instantiate_dbm__QuerierByAlias(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__QuerierByAlias(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__QuerierByAliasResponse
#define SOAP_TYPE_dbm__QuerierByAliasResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__QuerierByAliasResponse(struct soap*, struct dbm__QuerierByAliasResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__QuerierByAliasResponse(struct soap*, const struct dbm__QuerierByAliasResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__QuerierByAliasResponse(struct soap*, const char*, int, const struct dbm__QuerierByAliasResponse *, const char*);
SOAP_FMAC3 struct dbm__QuerierByAliasResponse * SOAP_FMAC4 soap_in_dbm__QuerierByAliasResponse(struct soap*, const char*, struct dbm__QuerierByAliasResponse *, const char*);

#define soap_write_dbm__QuerierByAliasResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__QuerierByAliasResponse(soap, data), 0) || soap_put_dbm__QuerierByAliasResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__QuerierByAliasResponse(struct soap*, const struct dbm__QuerierByAliasResponse *, const char*, const char*);

#define soap_read_dbm__QuerierByAliasResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__QuerierByAliasResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__QuerierByAliasResponse * SOAP_FMAC4 soap_get_dbm__QuerierByAliasResponse(struct soap*, struct dbm__QuerierByAliasResponse *, const char*, const char*);

#define soap_new_dbm__QuerierByAliasResponse(soap, n) ::soap_instantiate_dbm__QuerierByAliasResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__QuerierByAliasResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__QuerierByAliasResponse * SOAP_FMAC2 soap_instantiate_dbm__QuerierByAliasResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__QuerierByAliasResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__Querier
#define SOAP_TYPE_dbm__Querier (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__Querier(struct soap*, struct dbm__Querier *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__Querier(struct soap*, const struct dbm__Querier *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__Querier(struct soap*, const char*, int, const struct dbm__Querier *, const char*);
SOAP_FMAC3 struct dbm__Querier * SOAP_FMAC4 soap_in_dbm__Querier(struct soap*, const char*, struct dbm__Querier *, const char*);

#define soap_write_dbm__Querier(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__Querier(soap, data), 0) || soap_put_dbm__Querier(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__Querier(struct soap*, const struct dbm__Querier *, const char*, const char*);

#define soap_read_dbm__Querier(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__Querier(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__Querier * SOAP_FMAC4 soap_get_dbm__Querier(struct soap*, struct dbm__Querier *, const char*, const char*);

#define soap_new_dbm__Querier(soap, n) ::soap_instantiate_dbm__Querier(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__Querier(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__Querier * SOAP_FMAC2 soap_instantiate_dbm__Querier(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__Querier(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__QuerierResponse
#define SOAP_TYPE_dbm__QuerierResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__QuerierResponse(struct soap*, struct dbm__QuerierResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__QuerierResponse(struct soap*, const struct dbm__QuerierResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__QuerierResponse(struct soap*, const char*, int, const struct dbm__QuerierResponse *, const char*);
SOAP_FMAC3 struct dbm__QuerierResponse * SOAP_FMAC4 soap_in_dbm__QuerierResponse(struct soap*, const char*, struct dbm__QuerierResponse *, const char*);

#define soap_write_dbm__QuerierResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__QuerierResponse(soap, data), 0) || soap_put_dbm__QuerierResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__QuerierResponse(struct soap*, const struct dbm__QuerierResponse *, const char*, const char*);

#define soap_read_dbm__QuerierResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__QuerierResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__QuerierResponse * SOAP_FMAC4 soap_get_dbm__QuerierResponse(struct soap*, struct dbm__QuerierResponse *, const char*, const char*);

#define soap_new_dbm__QuerierResponse(soap, n) ::soap_instantiate_dbm__QuerierResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__QuerierResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__QuerierResponse * SOAP_FMAC2 soap_instantiate_dbm__QuerierResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__QuerierResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlFromMultiTable
#define SOAP_TYPE_dbm__ExeSqlFromMultiTable (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlFromMultiTable(struct soap*, struct dbm__ExeSqlFromMultiTable *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlFromMultiTable(struct soap*, const struct dbm__ExeSqlFromMultiTable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlFromMultiTable(struct soap*, const char*, int, const struct dbm__ExeSqlFromMultiTable *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlFromMultiTable * SOAP_FMAC4 soap_in_dbm__ExeSqlFromMultiTable(struct soap*, const char*, struct dbm__ExeSqlFromMultiTable *, const char*);

#define soap_write_dbm__ExeSqlFromMultiTable(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlFromMultiTable(soap, data), 0) || soap_put_dbm__ExeSqlFromMultiTable(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlFromMultiTable(struct soap*, const struct dbm__ExeSqlFromMultiTable *, const char*, const char*);

#define soap_read_dbm__ExeSqlFromMultiTable(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlFromMultiTable(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlFromMultiTable * SOAP_FMAC4 soap_get_dbm__ExeSqlFromMultiTable(struct soap*, struct dbm__ExeSqlFromMultiTable *, const char*, const char*);

#define soap_new_dbm__ExeSqlFromMultiTable(soap, n) ::soap_instantiate_dbm__ExeSqlFromMultiTable(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlFromMultiTable(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlFromMultiTable * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlFromMultiTable(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlFromMultiTable(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlFromMultiTableResponse
#define SOAP_TYPE_dbm__ExeSqlFromMultiTableResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlFromMultiTableResponse(struct soap*, struct dbm__ExeSqlFromMultiTableResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlFromMultiTableResponse(struct soap*, const struct dbm__ExeSqlFromMultiTableResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlFromMultiTableResponse(struct soap*, const char*, int, const struct dbm__ExeSqlFromMultiTableResponse *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlFromMultiTableResponse * SOAP_FMAC4 soap_in_dbm__ExeSqlFromMultiTableResponse(struct soap*, const char*, struct dbm__ExeSqlFromMultiTableResponse *, const char*);

#define soap_write_dbm__ExeSqlFromMultiTableResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlFromMultiTableResponse(soap, data), 0) || soap_put_dbm__ExeSqlFromMultiTableResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlFromMultiTableResponse(struct soap*, const struct dbm__ExeSqlFromMultiTableResponse *, const char*, const char*);

#define soap_read_dbm__ExeSqlFromMultiTableResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlFromMultiTableResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlFromMultiTableResponse * SOAP_FMAC4 soap_get_dbm__ExeSqlFromMultiTableResponse(struct soap*, struct dbm__ExeSqlFromMultiTableResponse *, const char*, const char*);

#define soap_new_dbm__ExeSqlFromMultiTableResponse(soap, n) ::soap_instantiate_dbm__ExeSqlFromMultiTableResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlFromMultiTableResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlFromMultiTableResponse * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlFromMultiTableResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlFromMultiTableResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlByWorldId
#define SOAP_TYPE_dbm__ExeSqlByWorldId (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlByWorldId(struct soap*, struct dbm__ExeSqlByWorldId *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlByWorldId(struct soap*, const struct dbm__ExeSqlByWorldId *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlByWorldId(struct soap*, const char*, int, const struct dbm__ExeSqlByWorldId *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlByWorldId * SOAP_FMAC4 soap_in_dbm__ExeSqlByWorldId(struct soap*, const char*, struct dbm__ExeSqlByWorldId *, const char*);

#define soap_write_dbm__ExeSqlByWorldId(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlByWorldId(soap, data), 0) || soap_put_dbm__ExeSqlByWorldId(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlByWorldId(struct soap*, const struct dbm__ExeSqlByWorldId *, const char*, const char*);

#define soap_read_dbm__ExeSqlByWorldId(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlByWorldId(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlByWorldId * SOAP_FMAC4 soap_get_dbm__ExeSqlByWorldId(struct soap*, struct dbm__ExeSqlByWorldId *, const char*, const char*);

#define soap_new_dbm__ExeSqlByWorldId(soap, n) ::soap_instantiate_dbm__ExeSqlByWorldId(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlByWorldId(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlByWorldId * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlByWorldId(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlByWorldId(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlByWorldIdResponse
#define SOAP_TYPE_dbm__ExeSqlByWorldIdResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlByWorldIdResponse(struct soap*, struct dbm__ExeSqlByWorldIdResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlByWorldIdResponse(struct soap*, const struct dbm__ExeSqlByWorldIdResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlByWorldIdResponse(struct soap*, const char*, int, const struct dbm__ExeSqlByWorldIdResponse *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlByWorldIdResponse * SOAP_FMAC4 soap_in_dbm__ExeSqlByWorldIdResponse(struct soap*, const char*, struct dbm__ExeSqlByWorldIdResponse *, const char*);

#define soap_write_dbm__ExeSqlByWorldIdResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlByWorldIdResponse(soap, data), 0) || soap_put_dbm__ExeSqlByWorldIdResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlByWorldIdResponse(struct soap*, const struct dbm__ExeSqlByWorldIdResponse *, const char*, const char*);

#define soap_read_dbm__ExeSqlByWorldIdResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlByWorldIdResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlByWorldIdResponse * SOAP_FMAC4 soap_get_dbm__ExeSqlByWorldIdResponse(struct soap*, struct dbm__ExeSqlByWorldIdResponse *, const char*, const char*);

#define soap_new_dbm__ExeSqlByWorldIdResponse(soap, n) ::soap_instantiate_dbm__ExeSqlByWorldIdResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlByWorldIdResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlByWorldIdResponse * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlByWorldIdResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlByWorldIdResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSql
#define SOAP_TYPE_dbm__ExeSql (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSql(struct soap*, struct dbm__ExeSql *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSql(struct soap*, const struct dbm__ExeSql *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSql(struct soap*, const char*, int, const struct dbm__ExeSql *, const char*);
SOAP_FMAC3 struct dbm__ExeSql * SOAP_FMAC4 soap_in_dbm__ExeSql(struct soap*, const char*, struct dbm__ExeSql *, const char*);

#define soap_write_dbm__ExeSql(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSql(soap, data), 0) || soap_put_dbm__ExeSql(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSql(struct soap*, const struct dbm__ExeSql *, const char*, const char*);

#define soap_read_dbm__ExeSql(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSql(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSql * SOAP_FMAC4 soap_get_dbm__ExeSql(struct soap*, struct dbm__ExeSql *, const char*, const char*);

#define soap_new_dbm__ExeSql(soap, n) ::soap_instantiate_dbm__ExeSql(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSql(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSql * SOAP_FMAC2 soap_instantiate_dbm__ExeSql(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSql(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlResponse
#define SOAP_TYPE_dbm__ExeSqlResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlResponse(struct soap*, struct dbm__ExeSqlResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlResponse(struct soap*, const struct dbm__ExeSqlResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlResponse(struct soap*, const char*, int, const struct dbm__ExeSqlResponse *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlResponse * SOAP_FMAC4 soap_in_dbm__ExeSqlResponse(struct soap*, const char*, struct dbm__ExeSqlResponse *, const char*);

#define soap_write_dbm__ExeSqlResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlResponse(soap, data), 0) || soap_put_dbm__ExeSqlResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlResponse(struct soap*, const struct dbm__ExeSqlResponse *, const char*, const char*);

#define soap_read_dbm__ExeSqlResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlResponse * SOAP_FMAC4 soap_get_dbm__ExeSqlResponse(struct soap*, struct dbm__ExeSqlResponse *, const char*, const char*);

#define soap_new_dbm__ExeSqlResponse(soap, n) ::soap_instantiate_dbm__ExeSqlResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlResponse * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlByDataOper
#define SOAP_TYPE_dbm__ExeSqlByDataOper (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlByDataOper(struct soap*, struct dbm__ExeSqlByDataOper *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlByDataOper(struct soap*, const struct dbm__ExeSqlByDataOper *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlByDataOper(struct soap*, const char*, int, const struct dbm__ExeSqlByDataOper *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlByDataOper * SOAP_FMAC4 soap_in_dbm__ExeSqlByDataOper(struct soap*, const char*, struct dbm__ExeSqlByDataOper *, const char*);

#define soap_write_dbm__ExeSqlByDataOper(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlByDataOper(soap, data), 0) || soap_put_dbm__ExeSqlByDataOper(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlByDataOper(struct soap*, const struct dbm__ExeSqlByDataOper *, const char*, const char*);

#define soap_read_dbm__ExeSqlByDataOper(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlByDataOper(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlByDataOper * SOAP_FMAC4 soap_get_dbm__ExeSqlByDataOper(struct soap*, struct dbm__ExeSqlByDataOper *, const char*, const char*);

#define soap_new_dbm__ExeSqlByDataOper(soap, n) ::soap_instantiate_dbm__ExeSqlByDataOper(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlByDataOper(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlByDataOper * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlByDataOper(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlByDataOper(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__ExeSqlByDataOperResponse
#define SOAP_TYPE_dbm__ExeSqlByDataOperResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__ExeSqlByDataOperResponse(struct soap*, struct dbm__ExeSqlByDataOperResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__ExeSqlByDataOperResponse(struct soap*, const struct dbm__ExeSqlByDataOperResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__ExeSqlByDataOperResponse(struct soap*, const char*, int, const struct dbm__ExeSqlByDataOperResponse *, const char*);
SOAP_FMAC3 struct dbm__ExeSqlByDataOperResponse * SOAP_FMAC4 soap_in_dbm__ExeSqlByDataOperResponse(struct soap*, const char*, struct dbm__ExeSqlByDataOperResponse *, const char*);

#define soap_write_dbm__ExeSqlByDataOperResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__ExeSqlByDataOperResponse(soap, data), 0) || soap_put_dbm__ExeSqlByDataOperResponse(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__ExeSqlByDataOperResponse(struct soap*, const struct dbm__ExeSqlByDataOperResponse *, const char*, const char*);

#define soap_read_dbm__ExeSqlByDataOperResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__ExeSqlByDataOperResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__ExeSqlByDataOperResponse * SOAP_FMAC4 soap_get_dbm__ExeSqlByDataOperResponse(struct soap*, struct dbm__ExeSqlByDataOperResponse *, const char*, const char*);

#define soap_new_dbm__ExeSqlByDataOperResponse(soap, n) ::soap_instantiate_dbm__ExeSqlByDataOperResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__ExeSqlByDataOperResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__ExeSqlByDataOperResponse * SOAP_FMAC2 soap_instantiate_dbm__ExeSqlByDataOperResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__ExeSqlByDataOperResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_dbm__StringArray
#define SOAP_TYPE_dbm__StringArray (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_dbm__StringArray(struct soap*, struct dbm__StringArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_dbm__StringArray(struct soap*, struct dbm__StringArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_dbm__StringArray(struct soap*, const char*, int, const struct dbm__StringArray *, const char*);
SOAP_FMAC3 struct dbm__StringArray * SOAP_FMAC4 soap_in_dbm__StringArray(struct soap*, const char*, struct dbm__StringArray *, const char*);

#define soap_write_dbm__StringArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_dbm__StringArray(soap, data), 0) || soap_put_dbm__StringArray(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_dbm__StringArray(struct soap*, const struct dbm__StringArray *, const char*, const char*);

#define soap_read_dbm__StringArray(soap, data) ( soap_begin_recv(soap) || !soap_get_dbm__StringArray(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct dbm__StringArray * SOAP_FMAC4 soap_get_dbm__StringArray(struct soap*, struct dbm__StringArray *, const char*, const char*);

#define soap_new_dbm__StringArray(soap, n) ::soap_instantiate_dbm__StringArray(soap, n, NULL, NULL, NULL)


#define soap_delete_dbm__StringArray(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct dbm__StringArray * SOAP_FMAC2 soap_instantiate_dbm__StringArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_dbm__StringArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#define soap_write_PointerToxsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToxsd__string(soap, data), 0) || soap_put_PointerToxsd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char **const*, const char*, const char*);

#define soap_read_PointerToxsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
